stories/urls.py
from django.conf.urls import url
from . import views

app_name = 'stories'


urlpatterns = [
    url(r'^home/$',views.home,name='home'),
    url(r'^$',views.stories_view,name='stories'),
]

website/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^licence/$',TemplateView.as_view(template_name='Licence.html'),name='licence'),
    url(r'^',include('stories.urls')),
]

stories/models.py
from django.db import models




class Story(models.Model):

    title       = models.CharField('story title',max_length=255)
    story_text  = models.TextField(default='')
    pub_date    = models.DateTimeField(auto_now_add=True)
    last_edited = models.DateTimeField(auto_now=True)
    tags        = models.TextField(default='',blank=True,null=True)
    seen        = models.IntegerField(default=0)
    votes       = models.IntegerField(default=0)
    featured    = models.BooleanField(default=True)


    def __str__(self):
        return self.title


    class Meta:
        verbose_name_plural = 'stories'
        ordering = ['-pub_date', 'title']

stories/views.py
from django.shortcuts import render
from .models import Story


def home(request):
    return render(request,'stories/base.html')

def stories_view(request):
    template = 'stories/story_list.html'
    qs = Story.objects.all()
    return render(request,template,{'stories':qs})

stories/templates/stories/base.html
{% extends 'base.html' %}
{% block title %}Stories | {{block.super}}{% endblock %}
{% block main %}

{% endblock %}

stories/templates/stories/story_list.html
{% extends 'base.html' %}
{% block title %}Stories | {{block.super}}{% endblock %}
{% block main %}
{% if stories %}
{% for story in stories %}
  <div class="panel panel-default">
    <div class='panel-heading'><h3>{{story}}</h3></div>
    <div class="panel-body">
          {{story.story_text}}
    </div>
    <div class="panel-footer">published: <time>{{story.last_edited}}</time></div>
  </div>
{% endfor %}
{% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Website.com{% endblock%}</title>
  {% include 'snippets/css.html' %}
</head>
<body>
  {% include 'nav.html' %}
<main>
<div class='container'>
{% block main %}{% endblock %}
</div>
</main>
{% include 'footer.html' %}
{% include 'snippets/js.html' %}
</body>
</html>

templates/footer.html
<div class='container-fluid'>
<footer id='footer-bottom'>
<div class='container'>
  <ul class="list-inline">
    <li class='inline-item'><h4><a href={% url 'stories:home'%}>&copy; 2017 Website.com</a></h4></li>
    <li class='inline-item'><a href={% url 'licence'%}>Licence</a></li>
  </ul>
</div>
</footer>

</div>

templates/nav.html
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle" data-toggle="collapse" data-target="#navHeaderCollapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
          <a class="navbar-brand" href="/" id="logo">Website.com</a>
      </div>

      <div class="collapse navbar-collapse"id='navHeaderCollapse'>
          <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="#">Home<span style="font-size:16px; margin-left: 10px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home left-padding-10"></span></a></li>
              <li><a href="#">Link 1</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Items <span style="padding-left:10px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-briefcase"></span><span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
                      <li><a href="#">View Items</a></li>
          <li><a href="#">Add Items</a></li>
        </ul>
      </li>
          </ul>
      </div>
  </div>
</nav>

templates/snippets/css.html
<link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<style>
  body{
    background-color: #fff;
  }
  .container-fluid{
    padding: 0px;
  }
  #footer-bottom{
    display:block;
    background-color: #7CB9E8;
    margin-bottom: 0px;
    margin-top: 30px;
    padding-top: 10px;

  }
  .inline-item a{
    color: white; !important
  }

</style>

templates/snippets/js.html
<script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">
</script>